<a href="https://colab.research.google.com/github/Atharv-S8/ML/blob/main/abc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
print("Hi")

Hi


In [13]:
import numpy as np
arr=np.arange(0,11)
arr
arr[8]
arr[1:5]
arr[0:5]


array([0, 1, 2, 3, 4])

In [14]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Import  notes on slices
slice_of_arr=arr[0:6]
#show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
#change slice
slice_of_arr[:]=99
#show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])